### ISSUE TITLE
Cannot link error

### ISSUE THREAD

**Issue by icebal** [st42/termux-sudo#11]
getting an error when using systemless MagiskSU on 7.1.2 running anything with sudo. Su -c command works by itself just fine.

CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib64/libunwind.so"...

**Comment by icebal** [comment]
this error is repeated through many lines of your script, if you want the whole thing let me know :)

**Comment by st42** [comment]
Sorry it took so long to address this issue. This isn't a sudo issue. This is an issue with Termux and android 7.1.1 and later. sudo is just a bash script that mimics the behavior of the linux sudo binary. This is an issue for the developer of Termux.

**Comment by icebal** [comment]
woot, will do! i'll bring it to his attention :D

**Comment by WordlessEcho** [comment]
```Shell
$ sudo
CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib/libunwind.so"...
/data/data/com.termux/files/usr/bin/sudo: line 65: 29091 Aborted                 $SU -c "$MOUNT_RW"
CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib/libunwind.so"...
/data/data/com.termux/files/usr/bin/sudo: line 65: 29093 Aborted                 $SU -c "mkdir $ROOT_HOME"
CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib/libunwind.so"...
/data/data/com.termux/files/usr/bin/sudo: line 65: 29096 Aborted                 $SU -c "chmod 700 $ROOT_HOME"
CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib/libunwind.so"...
/data/data/com.termux/files/usr/bin/sudo: line 65: 29099 Aborted                 $SU -c "echo -e $BASHRC > $ROOT_HOME/.bashrc"
CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib/libunwind.so"...
/data/data/com.termux/files/usr/bin/sudo: line 65: 29114 Aborted                 $SU -c "chmod 700 $ROOT_HOME/.bashrc"
CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib/libunwind.so"...
/data/data/com.termux/files/usr/bin/sudo: line 65: 29119 Aborted                 $SU -c "$MOUNT_RO"
```

**Comment by st42** [comment]
I have attempted to fix this within termux-sudo. It may just be a work around at the moment, but give it a try as I have no way to test this fix myself.

**Comment by st42** [comment]
I am reopening this issue until I get feedback on this latest commit

**Comment by icebal** [comment]
Latest commit still has the issue, but nowhere near the errors.

CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol
"XzUnpacker_Construct" referenced by "/system/lib64/libunwind.so"...
CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol
"XzUnpacker_Construct" referenced by "/system/lib64/libunwind.so"...
/data/data/com.termux/files/usr/bin/sudo: line 93:  9680 Aborted
      (core dumped) $SU -c "$CMDLINE"

**Comment by st42** [comment]
I am re-closing this issue because it appears that this issue with 7.1.1+ will have to fixed in Termux.

**Comment by icebal** [comment]
it is working now :) strace still shows the errors, but doesn't impact function, nor shows when running regularly.

**Comment by st42** [comment]
Is this before or after the latest commit

**Comment by icebal** [comment]
before you reverted. testing out the latest right now

**Comment by st42** [comment]
@icebal 
If the latest commit doesn't work and I expect it wont, I would like to try something before I undo the reverted commit. Could you give me the location of your su binary, not the linked location of `/sbin/su`
use the following to find it:
`ls -la /sbin/su`

**Comment by icebal** [comment]
fresh pull works still for me. willing to try anything you think will help future-proof it :)
i'm using magisk, so 
/sbin/su -> /sbin/magisk
/sbin/magisk -> /sbin_orig/magisk
/sbin_orig/magisk is the end of the symlink train....

**Comment by st42** [comment]
If the latest commit works the developer of Termux must have fixed the `CANNOT LINK EXECUTABLE` error internally. So the work around of the commit I reverted is no longer necessary. Thanks for the su binary location I'll keep it in mind for future reference if the need arises.

**Comment by liwanglin12** [comment]
same issue there...

**Comment by bruce965** [comment]
I'm using Magisk, replacing the section that looks for `su` executable with `SU=su` seems to work for me.

**Comment by papuruth** [comment]
It is working but it gives this error im using magisk root
sudo su
CANNOT LINK EXECUTABLE "/sbin/su": "/data/data/com.termux/files/usr/lib/libcrypto.so.1.0.0" is 64-bit instead of 32-bit
#
